[global]
timeout = 30
index-url = https://artifactory.nexign.com/artifactory/api/pypi/pypi/simple
trusted-host = artifactory.nexign.com
extra-index-url= https://artifactory.nexign.com:443/artifactory/generic-dev-local/ps/rnd/mfactory
