{% extends "common/templates/Dockerfile.common.j2" %}
{% block specific %}
ENV PATH=/usr/sbin:$PATH
EXPOSE 8080
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/default.conf /etc/nginx/http.d/default.conf
RUN apk add --no-cache nginx &&\
    mkdir -p /var/lib/nginx/tmp/client_body &&\
    touch /var/run/nginx.pid &&\
    chmod -R 777 /var/lib/nginx/ /var/log/nginx/ /var/run/ &&\
    chown -R 11200:11200 /var/run/nginx.pid /var/lib/nginx/ /var/log/nginx/
CMD ["nginx", "-g", "daemon off;"]
{% endblock %}
