{% extends "common/templates/Dockerfile.common.j2" %}

{% block extra_env %}
ENV PATH=/usr/sbin:$PATH
{% endblock %}

{% block specific %}
EXPOSE 8080

USER 0
RUN mkdir -p /var/lib/nginx/tmp/client_body && \
    touch /var/run/nginx.pid && \
    chmod -R 777 /var/lib/nginx/ /var/log/nginx/ /var/run/ && \
    chown -R 11200:11200 /var/run/nginx.pid /var/lib/nginx/ /var/log/nginx/

USER 11200
CMD ["nginx", "-g", "daemon off;"]
{% endblock %}
