{% extends "common/templates/Dockerfile.common.j2" %}
{% block package_installation %}
USER 0
RUN rm -f /etc/yum.repos.d/* && \
    curl --connect-timeout 30 http://repo.nexign.com/scripts/add-ubi9-repo.sh | sh && \
    curl --connect-timeout 30 http://repo.nexign.com/scripts/add-almalinux-repo.sh | sh && \
    curl --connect-timeout 30 http://repo.nexign.com/scripts/add-elrepo-repo.sh | sh && \
    update-ca-trust force-enable && \
    update-ca-trust extract && \
    {{ package_manager }} remove nodejs -y && \
    {{ package_manager }} upgrade -y && \
    {{ package_manager }} --enablerepo=elrepo-kernel install -y --nodocs {{ packages | join(' ') }} && \
    {{ package_manager }} clean all
{% endblock %}
{% block specific %}
ENV APP_ROOT=/opt/app-root
ENV PATH=/opt/app-root/src/bin:/opt/app-root/bin:$HOME/.local/bin/:$PATH \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    PIP_NO_CACHE_DIR=off
USER 0
RUN pip install virtualenv yq && \
    python3 -m virtualenv ${APP_ROOT} && \
    chown -R 11200:0 ${APP_ROOT}
RUN useradd -m -u 11200 mf-user -s /bin/bash && \
    mkdir -p /data/app && \
    chown mf-user:mf-user /data/app
{% endblock %}
