{% extends "common/templates/Dockerfile.common.j2" %}
{% block specific %}
ARG VERSION
ENV PATH=/opt/gradle/bin:$PATH
RUN apk add --no-cache bash make curl jq
RUN apk upgrade libssl3 libcrypto3
WORKDIR /data/gradle
{% endblock %}
